In [60]:
import pandas as pd
import numpy as np

In [61]:
deaths = pd.read_csv("deaths_by_year_state_gender_race_state_2010-2018.txt", sep = "\t")

In [62]:
deaths

,Notes,Year,Year Code,State,State Code,Ten-Year Age Groups,Ten-Year Age Groups Code,Gender,Gender Code,Race,Race Code,Deaths,Population,Crude Rate
0,NaN,2010.0,2010.0,Alabama,1.0,< 1 year,1,Female,F,Black or African American,2054-5,113.0,9648,1171.2
1,NaN,2010.0,2010.0,Alabama,1.0,< 1 year,1,Female,F,White,2106-3,123.0,19239,639.3
2,NaN,2010.0,2010.0,Alabama,1.0,< 1 year,1,Male,M,Black or African American,2054-5,137.0,9856,1390.0
3,NaN,2010.0,2010.0,Alabama,1.0,< 1 year,1,Male,M,White,2106-3,146.0,19869,734.8
4,NaN,2010.0,2010.0,Alabama,1.0,1-4 years,1-4,Female,F,Black or African American,2054-5,11.0,38436,Unreliable
5,NaN,2010.0,2010.0,Alabama,1.0,1-4 years,1-4,Female,F,White,2106-3,19.0,78568,Unreliable
6,NaN,2010.0,2010.0,Alabama,1.0,1-4 years,1-4,Male,M,Black or African American,2054-5,19.0,39170,Unreliable
7,NaN,2010.0,2010.0,Alabama,1.0,1-4 years,1-4,Male,M,White,2106-3,30.0,82499,36.4
8,NaN,2010.0,2010.0,Alabama,1.0,5-14 years,5-14,Female,F,Black or African American,2054-5,21.0,96816,21.7
9,NaN,2010.0,2010.0,Alabama,1.0,5-14 years,5-14,Female,F,White,2106-3,37.0,202812,18.2
10,NaN,2010.0,2010.0,Alabama,1.0,5-14 years,5-14,Male,M,Black or African American,2054-5,31.0,99812,31.1
11,NaN,2010.0,2010.0,Alabama,1.0,5-14 years,5-14,Male,M,White,2106-3,47.0,213440,22.0
12,NaN,2010.0,2010.0,Alabama,1.0,15-24 years,15-24,Female,F,Black or African American,2054-5,71.0,111303,63.8
13,NaN,2010.0,2010.0,Alabama,1.0,15-24 years,15-24,Female,F,White,2106-3,120.0,217434,55.2
14,NaN,2010.0,2010.0,Alabama,1.0,15-24 years,15-24,Male,M,Black or African American,2054-5,178.0,106330,167.4
15,NaN,2010.0,2010.0,Alabama,1.0,15-24 years,15-24,Male,M,White,2106-3,257.0,227918,112.8
16,NaN,2010.0,2010.0,Alabama,1.0,25-34 years,25-34,Female,F,Black or African American,2054-5,114.0,95452,119.4
17,NaN,2010.0,2010.0,Alabama,1.0,25-34 years,25-34,Female,F,White,2106-3,221.0,204528,108.1
18,NaN,2010.0,2010.0,Alabama,1.0,25-34 years,25-34,Male,M,Black or African American,2054-5,200.0,80683,247.9
19,NaN,2010.0,2010.0,Alabama,1.0,25-34 years,25-34,Male,M,White,2106-3,462.0,210492,219.5
20,NaN,2010.0,2010.0,Alabama,1.0,35-44 years,35-44,Female,F,Black or African American,2054-5,238.0,88645,268.5
21,NaN,2010.0,2010.0,Alabama,1.0,35-44 years,35-44,Female,F,White,2106-3,435.0,218975,198.7
22,NaN,2010.0,2010.0,Alabama,1.0,35-44 years,35-44,Male,M,Black or African American,2054-5,277.0,73361,377.6
23,NaN,2010.0,2010.0,Alabama,1.0,35-44 years,35-44,Male,M,White,2106-3,665.0,222558,298.8
24,NaN,2010.0,2010.0,Alabama,1.0,45-54 years,45-54,Female,F,Black or African American,2054-5,535.0,96633,553.6
25,NaN,2010.0,2010.0,Alabama,1.0,45-54 years,45-54,Female,F,White,2106-3,1047.0,252403,414.8
26,NaN,2010.0,2010.0,Alabama,1.0,45-54 years,45-54,Male,M,Black or African American,2054-5,723.0,80799,894.8
27,NaN,2010.0,2010.0,Alabama,1.0,45-54 years,45-54,Male,M,White,2106-3,1710.0,250831,681.7
28,NaN,2010.0,2010.0,Alabama,1.0,55-64 years,55-64,Female,F,Asian or Pacific Islander,A-PI,12.0,3197,Unreliable
29,NaN,2010.0,2010.0,Alabama,1.0,55-64 years,55-64,Female,F,Black or African American,2054-5,784.0,73342,1069.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24231,http://wonder.cdc.gov/wonder/help/ucd.html#Ass...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24232,3. Death rates are flagged as Unreliable when ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24233,http://wonder.cdc.gov/wonder/help/ucd.html#Unr...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24234,"4. Deaths of persons with Age ""Not Stated"" are...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24235,"so are not included in age-specific counts, ag...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24236,http://wonder.cdc.gov/wonder/help/ucd.html#Not...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24237,5. Information included on the death certifica...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24238,"funeral director as provided by an informant, ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24239,of observation. Race and ethnicity information...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24240,are inconsistent between these two data source...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24241,http://wonder.cdc.gov/wonder/help/ucd.html#Rac...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24242,6. The population figures for year 2018 are br...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24243,"postcensal series released by NCHS on June 25,...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24244,"1 resident population, from the Vintage 2017 p...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24245,year 2016 are bridged-race estimates of the Ju...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24246,"on June 26, 2017. The population figures for y...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24247,Vintage 2015 postcensal series released by NCH...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24248,"estimates of the July 1 resident population, f...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24249,population figures for year 2013 are bridged-r...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24250,"series released by NCHS on June 26, 2014. The ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24251,"population, from the Vintage 2012 postcensal s...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24252,bridged-race estimates of the July 1 resident ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24253,2012. Population figures for 2010 are April 1 ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24254,"estimates of the July 1 resident population, f...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24255,"October 26, 2012. Population figures for 2000 ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24256,intercensal series of July 1 estimates. Popula...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24257,<br/><b>Note:</b> Rates and population figures...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24258,use of the population estimates which were ava...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24259,7. The population figures used in the calculat...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24260,resident population that is under one year of ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Looks like we have a lot of non-data at the end of the text document that needs to be removed. First, the cutoff between read data and descriptive text needs to be found:

In [63]:
deaths.tail(80)

,Notes,Year,Year Code,State,State Code,Ten-Year Age Groups,Ten-Year Age Groups Code,Gender,Gender Code,Race,Race Code,Deaths,Population,Crude Rate
24181,NaN,2018.0,2018.0,Wyoming,56.0,15-24 years,15-24,Male,M,White,2106-3,48.0,35779,134.2
24182,NaN,2018.0,2018.0,Wyoming,56.0,25-34 years,25-34,Female,F,White,2106-3,22.0,34567,63.6
24183,NaN,2018.0,2018.0,Wyoming,56.0,25-34 years,25-34,Male,M,White,2106-3,65.0,37268,174.4
24184,NaN,2018.0,2018.0,Wyoming,56.0,35-44 years,35-44,Female,F,White,2106-3,49.0,32926,148.8
24185,NaN,2018.0,2018.0,Wyoming,56.0,35-44 years,35-44,Male,M,American Indian or Alaska Native,1002-5,10.0,998,Unreliable
24186,NaN,2018.0,2018.0,Wyoming,56.0,35-44 years,35-44,Male,M,White,2106-3,87.0,35608,244.3
24187,NaN,2018.0,2018.0,Wyoming,56.0,45-54 years,45-54,Female,F,American Indian or Alaska Native,1002-5,10.0,846,Unreliable
24188,NaN,2018.0,2018.0,Wyoming,56.0,45-54 years,45-54,Female,F,White,2106-3,114.0,29923,381.0
24189,NaN,2018.0,2018.0,Wyoming,56.0,45-54 years,45-54,Male,M,White,2106-3,162.0,31539,513.6
24190,NaN,2018.0,2018.0,Wyoming,56.0,55-64 years,55-64,Female,F,White,2106-3,258.0,38207,675.3
24191,NaN,2018.0,2018.0,Wyoming,56.0,55-64 years,55-64,Male,M,White,2106-3,394.0,38424,1025.4
24192,NaN,2018.0,2018.0,Wyoming,56.0,65-74 years,65-74,Female,F,American Indian or Alaska Native,1002-5,10.0,476,Unreliable
24193,NaN,2018.0,2018.0,Wyoming,56.0,65-74 years,65-74,Female,F,White,2106-3,387.0,27794,1392.4
24194,NaN,2018.0,2018.0,Wyoming,56.0,65-74 years,65-74,Male,M,American Indian or Alaska Native,1002-5,10.0,430,Unreliable
24195,NaN,2018.0,2018.0,Wyoming,56.0,65-74 years,65-74,Male,M,White,2106-3,588.0,28514,2062.1
24196,NaN,2018.0,2018.0,Wyoming,56.0,75-84 years,75-84,Female,F,American Indian or Alaska Native,1002-5,16.0,184,Unreliable
24197,NaN,2018.0,2018.0,Wyoming,56.0,75-84 years,75-84,Female,F,White,2106-3,590.0,13718,4300.9
24198,NaN,2018.0,2018.0,Wyoming,56.0,75-84 years,75-84,Male,M,White,2106-3,634.0,12165,5211.7
24199,NaN,2018.0,2018.0,Wyoming,56.0,85+ years,85+,Female,F,White,2106-3,858.0,6517,13165.6
24200,NaN,2018.0,2018.0,Wyoming,56.0,85+ years,85+,Male,M,White,2106-3,601.0,3907,15382.6
24201,---,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24202,"Dataset: Underlying Cause of Death, 1999-2018",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24203,Query Parameters:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24204,"Title: Deaths by Year, State, Age, Gender, and...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24205,Year/Month: 2010; 2011; 2012; 2013; 2014; 2015...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24206,Group By: Year; State; Ten-Year Age Groups; Ge...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24207,Show Totals: Disabled,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24208,Show Zero Values: False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24209,Show Suppressed: False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24210,"Calculate Rates Per: 100,000",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24231,http://wonder.cdc.gov/wonder/help/ucd.html#Ass...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24232,3. Death rates are flagged as Unreliable when ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24233,http://wonder.cdc.gov/wonder/help/ucd.html#Unr...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24234,"4. Deaths of persons with Age ""Not Stated"" are...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24235,"so are not included in age-specific counts, ag...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24236,http://wonder.cdc.gov/wonder/help/ucd.html#Not...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24237,5. Information included on the death certifica...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24238,"funeral director as provided by an informant, ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24239,of observation. Race and ethnicity information...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24240,are inconsistent between these two data source...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24241,http://wonder.cdc.gov/wonder/help/ucd.html#Rac...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24242,6. The population figures for year 2018 are br...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24243,"postcensal series released by NCHS on June 25,...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24244,"1 resident population, from the Vintage 2017 p...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24245,year 2016 are bridged-race estimates of the Ju...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24246,"on June 26, 2017. The population figures for y...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24247,Vintage 2015 postcensal series released by NCH...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24248,"estimates of the July 1 resident population, f...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24249,population figures for year 2013 are bridged-r...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24250,"series released by NCHS on June 26, 2014. The ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24251,"population, from the Vintage 2012 postcensal s...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24252,bridged-race estimates of the July 1 resident ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24253,2012. Population figures for 2010 are April 1 ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24254,"estimates of the July 1 resident population, f...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24255,"October 26, 2012. Population figures for 2000 ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24256,intercensal series of July 1 estimates. Popula...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24257,<br/><b>Note:</b> Rates and population figures...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24258,use of the population estimates which were ava...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24259,7. The population figures used in the calculat...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24260,resident population that is under one year of ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [64]:
deaths = deaths[:24201]

In [65]:
deaths.tail()

,Notes,Year,Year Code,State,State Code,Ten-Year Age Groups,Ten-Year Age Groups Code,Gender,Gender Code,Race,Race Code,Deaths,Population,Crude Rate
24196,NaN,2018.0,2018.0,Wyoming,56.0,75-84 years,75-84,Female,F,American Indian or Alaska Native,1002-5,16.0,184,Unreliable
24197,NaN,2018.0,2018.0,Wyoming,56.0,75-84 years,75-84,Female,F,White,2106-3,590.0,13718,4300.9
24198,NaN,2018.0,2018.0,Wyoming,56.0,75-84 years,75-84,Male,M,White,2106-3,634.0,12165,5211.7
24199,NaN,2018.0,2018.0,Wyoming,56.0,85+ years,85+,Female,F,White,2106-3,858.0,6517,13165.6
24200,NaN,2018.0,2018.0,Wyoming,56.0,85+ years,85+,Male,M,White,2106-3,601.0,3907,15382.6

Check to see if appropriate types are assigned:

In [66]:
deaths.dtypes

Notes                        object
Year                        float64
Year Code                   float64
State                        object
State Code                  float64
Ten-Year Age Groups          object
Ten-Year Age Groups Code     object
Gender                       object
Gender Code                  object
Race                         object
Race Code                    object
Deaths                      float64
Population                   object
Crude Rate                   object
dtype: object

Looks like Population may need to be an integer, but let's see what kinds of values are in each column:

In [67]:
for c in deaths[['Notes','State','Ten-Year Age Groups','Ten-Year Age Groups Code',
                 'Gender','Gender Code','Race','Race Code','Population','Crude Rate']].columns:
    print("---- %s ---" % c)
    print(deaths[c].value_counts())

---- Notes ---
Series([], Name: Notes, dtype: int64)
---- State ---
California              750
Texas                   664
New York                664
Washington              661
North Carolina          660
Arizona                 657
Florida                 640
Minnesota               637
Michigan                630
Oklahoma                617
Wisconsin               593
Virginia                579
Nevada                  570
Colorado                565
Illinois                561
Pennsylvania            561
New Jersey              554
Oregon                  548
Georgia                 548
Ohio                    543
Maryland                540
Louisiana               529
Missouri                525
Kansas                  516
Massachusetts           499
Tennessee               499
New Mexico              494
South Carolina          494
Indiana                 485
Alabama                 479
Mississippi             468
Arkansas                448
Utah                    437
Alaska                  434
Connecticut             433
Kentucky                416
Iowa                    402
Nebraska                398
Hawaii                  344
Delaware                333
South Dakota            326
West Virginia           319
Montana                 314
Rhode Island            294
District of Columbia    287
North Dakota            285
Idaho                   284
Wyoming                 203
Maine                   180
New Hampshire           179
Vermont                 155
Name: State, dtype: int64
---- Ten-Year Age Groups ---
65-74 years    2880
75-84 years    2851
55-64 years    2802
85+ years      2729
45-54 years    2573
35-44 years    2288
25-34 years    2114
< 1 year       1892
15-24 years    1868
5-14 years     1142
1-4 years      1039
Not Stated       23
Name: Ten-Year Age Groups, dtype: int64
---- Ten-Year Age Groups Code ---
65-74    2880
75-84    2851
55-64    2802
85+      2729
45-54    2573
35-44    2288
25-34    2114
1        1892
15-24    1868
5-14     1142
1-4      1039
NS         23
Name: Ten-Year Age Groups Code, dtype: int64
---- Gender ---
Male      12529
Female    11672
Name: Gender, dtype: int64
---- Gender Code ---
M    12529
F    11672
Name: Gender Code, dtype: int64
---- Race ---
White                               9595
Black or African American           7053
Asian or Pacific Islander           4420
American Indian or Alaska Native    3133
Name: Race, dtype: int64
---- Race Code ---
2106-3    9595
2054-5    7053
A-PI      4420
1002-5    3133
Name: Race Code, dtype: int64
---- Population ---
Not Applicable    23
189                8
262                7
141                7
272                6
130                6
846                6
240                6
135                6
214                6
424                6
665                6
109                6
1617               6
3268               6
1297               6
535                6
384                6
606                6
587                6
2768               6
533                6
420                6
188                5
308                5
3324               5
862                5
457                5
310                5
2452               5
                  ..
10449              1
399302             1
31086              1
189916             1
36229              1
356362             1
206405             1
53258              1
47190              1
248677             1
388437             1
39969              1
11824              1
721623             1
154563             1
99619              1
135414             1
53987              1
44236              1
367428             1
37846              1
17830              1
26875              1
31259              1
216151             1
469729             1
148916             1
168644             1
2853               1
29830              1
Name: Population, Length: 20714, dtype: int64
---- Crude Rate ---
Unreliable        3872
Not Applicable      23
18.9                15
13.6                14
11.2                13
34.2                13
19.5                12
14.9                12
11.6                12
10.7                11
18.6                11
15.9                11
10.9                10
44.8                10
16.5                10
10.6                10
9.6                 10
37.3                10
20.7                10
15.4                10
15.7                10
11.5                10
53.3                10
21.8                10
9.9                 10
45.0                 9
14.0                 9
29.9                 9
9.0                  9
9.4                  9
                  ...
411.4                1
752.8                1
186.8                1
856.9                1
13962.5              1
827.3                1
1881.8               1
4707.8               1
12373.5              1
12770.6              1
194.4                1
3392.8               1
14751.3              1
936.0                1
5923.2               1
2715.6               1
9463.7               1
1201.2               1
2808.4               1
3064.7               1
1804.3               1
609.2                1
2733.5               1
1566.6               1
1371.4               1
12349.6              1
2775.6               1
961.0                1
1331.9               1
359.8                1
Name: Crude Rate, Length: 13857, dtype: int64

"Unreliable" and "Not Applicable" are in crude rate, "Not Applicable" is in Population, and "Not Stated" is within Age Groups.  According to the documentation at [CDC Wonder](https://wonder.cdc.gov/controller/datarequest/D76;jsessionid=6989CE698643E7A64442C371308570C4), "Not Applicable" and "Unreliable" happens when there are 20 or fewer cases. This being the case, I think we're safe to remove without ruining the results. "Not Stated" for Age Groups means they are included in total counts and rates, but are not distributed among age groups.  This, too, can be removed.  

Finally, since several of the columns are duplicate "code" versions, we can do away with them.

In [68]:
deaths = deaths[deaths['Population'] != "Not Applicable"]
deaths = deaths[deaths['Crude Rate'] != "Not Applicable"]
deaths = deaths[deaths['Crude Rate'] != "Unreliable"]
deaths = deaths[deaths['Ten-Year Age Groups'] != "Not Stated"]

In [69]:
deaths.dtypes

Notes                        object
Year                        float64
Year Code                   float64
State                        object
State Code                  float64
Ten-Year Age Groups          object
Ten-Year Age Groups Code     object
Gender                       object
Gender Code                  object
Race                         object
Race Code                    object
Deaths                      float64
Population                   object
Crude Rate                   object
dtype: object

In [70]:
deaths = deaths[['Year','State','Ten-Year Age Groups','Gender','Race','Deaths','Population','Crude Rate']]

With Population and Crude Rate scrubbed of strings, we can convert to int and float.

In [72]:
deaths['Population'] = deaths['Population'].astype(int)
deaths['Crude Rate'] = deaths['Crude Rate'].astype(float)

One more check on the value counts of the object columns:

In [73]:
for c in deaths[['State','Ten-Year Age Groups','Gender','Race']].columns:
    print("---- %s ---" % c)
    print(deaths[c].value_counts())

---- State ---
California              708
Texas                   618
New York                610
Arizona                 599
Washington              598
North Carolina          590
Florida                 566
Michigan                564
Oklahoma                553
Minnesota               541
Illinois                514
Georgia                 508
Wisconsin               507
Virginia                488
Pennsylvania            485
New Jersey              481
Ohio                    475
Colorado                467
Maryland                456
Nevada                  445
Oregon                  434
Louisiana               433
Massachusetts           431
Missouri                431
Tennessee               424
Kansas                  420
Indiana                 415
South Carolina          397
Alabama                 387
Connecticut             378
New Mexico              378
Arkansas                358
Kentucky                358
Mississippi             354
Alaska                  298
Iowa                    290
Hawaii                  284
Delaware                280
Montana                 272
Utah                    271
West Virginia           266
Nebraska                264
South Dakota            262
District of Columbia    244
Rhode Island            219
North Dakota            211
Idaho                   175
Maine                   162
New Hampshire           158
Wyoming                 148
Vermont                 131
Name: State, dtype: int64
---- Ten-Year Age Groups ---
75-84 years    2535
65-74 years    2522
55-64 years    2456
85+ years      2393
45-54 years    2230
35-44 years    1935
25-34 years    1738
< 1 year       1522
15-24 years    1492
5-14 years      841
1-4 years       642
Name: Ten-Year Age Groups, dtype: int64
---- Gender ---
Male      10573
Female     9733
Name: Gender, dtype: int64
---- Race ---
White                               9060
Black or African American           6268
Asian or Pacific Islander           3023
American Indian or Alaska Native    1955
Name: Race, dtype: int64

And for the numeric columns, let's check out the description:

In [74]:
deaths.describe()

               Year        Deaths    Population    Crude Rate
count  20306.000000  20306.000000  2.030600e+04  20306.000000
mean    2014.054122   1170.253718  1.325121e+05   2527.513784
std        2.585123   3022.014161  2.368752e+05   4070.469920
min     2010.000000     20.000000  6.300000e+01      5.500000
25%     2012.000000     51.000000  9.836500e+03    176.625000
50%     2014.000000    173.000000  4.279800e+04    649.950000
75%     2016.000000    884.750000  1.545565e+05   2616.000000
max     2018.000000  45924.000000  2.264572e+06  31746.000000

Finally, those column names need updating to work better with code:

In [77]:
deaths.columns

Index(['Year', 'State', 'Ten-Year Age Groups', 'Gender', 'Race', 'Deaths',
       'Population', 'Crude Rate'],
      dtype='object')

In [78]:
deaths.columns = ['year','state','age_group','gender','race','deaths','population','crude_rate']

Seems appropriate to write to .csv before checking out some of the trends and findings.

In [79]:
deaths.to_csv('deaths.csv', index = False)